### ISSUE TITLE
About from `src.pySRM.pysrm.segment import ...`

### ISSUE THREAD

**Issue by ranabanik** [mjoppich/pIMZ#3]
In the examples in some of the .ipnbs there are these library imports. 

`from src.pySRM.pysrm.segment import IMZMLExtract, SpectraRegion, ProteinWeights, CombinedSpectra`
what does `src` refer to? 
for example, the `ProteinWeights` class is present in `pIMZ/regions.py`

And the only src I found after installation is `cIMZ/src` which actually has .cpp and .h extension C files

**Comment by mjoppich** [comment]
I would recommend to follow the example from

https://github.com/mjoppich/pIMZ/blob/master/examples/IMZMLprocess.theo_weights.ipynb

since this is the most documented one (and the one we are currently working with, too). Bear in mind that pIMZ is still in active development - but we're glad you're interested in it!

Since you installed pIMZ with pip, you can simply use

`from pIMZ.regions import SpectraRegion, ProteinWeights`

The cIMZ library is compiled during the build process and should not worry you ;)

**Comment by ranabanik** [comment]
Thanks for sharing the example.
Just asking as a beginner in MSI, are there resources that explain the procedures from data/imaging perspective?

**Comment by mjoppich** [comment]
You mean regarding how data acquisition works?

Neumann, E. K., Djambazova, K. V., Caprioli, R. M., & Spraggins, J. M. (2020). Multimodal Imaging Mass Spectrometry: Next Generation Molecular Mapping in Biology and Medicine. Journal of the American Society for Mass Spectrometry. https://doi.org/10.1021/jasms.0c00232

Otherwise, what I found quite an interesting read regarding ML in IMS:

Verbeeck, N., Caprioli, R. M., & Van de Plas, R. (2019). Unsupervised machine learning for exploratory data analysis in imaging mass spectrometry. Mass Spectrometry Reviews. https://doi.org/10.1002/mas.21602

As already mentioned, pIMZ is still in active development. We are currently improving our clustering techniques, but the basic stuff is already there.

What makes any development quite hard is the availability of (good) datasets. There are, unfortunately, not many :\
